# Generated by Django 3.0.1 on 2019-12-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191226_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
