# Generated by Django 3.0.1 on 2020-01-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_teampreference_is_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
