# Generated by Django 3.0.1 on 2020-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_team_mappings_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammapping',
            name='numeric_external_identifier',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teammapping',
            name='string_external_idenifier',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
