# Generated by Django 3.0.1 on 2020-01-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_team_mappings_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammapping',
            old_name='string_external_idenifier',
            new_name='string_external_identifier',
        ),
    ]
