# Generated by Django 3.0.1 on 2020-04-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_fixture_status_mappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='is_ongoing',
        ),
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.FixtureStatus'),
            preserve_default=False,
        ),
    ]
