# Generated by Django 3.0.1 on 2020-01-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_apis')
    ]

    operations = [
        migrations.AddField(
            model_name='teammapping',
            name='numeric_external_identifier',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammapping',
            name='string_external_idenifier',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
