# Generated by Django 3.0.1 on 2020-04-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_team_mappings_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureStatusMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_external_identifier', models.IntegerField(default=None, null=True)),
                ('string_external_identifier', models.CharField(default=None, max_length=100, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Api')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FixtureStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
