# Generated by Django 3.0.1 on 2020-03-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_apis_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammapping',
            old_name='team',
            new_name='value',
        ),
        migrations.AddField(
            model_name='fixture',
            name='is_ongoing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestaudit',
            name='response_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestaudit',
            name='successful',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestaudit',
            name='url',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='current_version_iter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestaudit',
            name='hashed_response',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FixtureMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_external_identifier', models.IntegerField(default=None, null=True)),
                ('string_external_identifier', models.CharField(default=None, max_length=100, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Api')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fixture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
