# Generated by Django 3.0.1 on 2020-01-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_auto_20200104_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammapping',
            name='numeric_external_identifier',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='teammapping',
            name='string_external_idenifier',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
