# Generated by Django 3.0.1 on 2020-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_auto_20200425_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
