# Generated by Django 3.0.1 on 2020-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teammapping_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammapping',
            name='is_active',
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
