# Generated by Django 3.0.1 on 2020-03-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200105_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLimitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='request_interval_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='requests_per_minute',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Api')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField()),
                ('hashed_response', models.CharField(max_length=100)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Api')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RequestType')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('kickoff_time_utc', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_away_team', to='home.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_home_team', to='home.Team')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='request_limit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.RequestLimitType'),
        ),
    ]
