# Generated by Django 3.0.1 on 2020-03-20 03:59
import sys
from django.db import migrations


def load_request_limit_types(apps, schema_editor):
    RequestLimitType = apps.get_model('home', 'RequestLimitType')
    
    limit_type_staggered = RequestLimitType(id=0, description="staggered")
    limit_type_staggered.save()

    limit_type_per_minute = RequestLimitType(id=1, description="per minute")
    limit_type_per_minute.save()


def delete_request_limit_types(apps, schema_editor):
    RequestLimitType = apps.get_model('home', 'RequestLimitType')
    RequestLimitType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200311_0436'),
    ]

    operations = [
        migrations.RunPython(load_request_limit_types, delete_request_limit_types)
    ] if 'test' not in sys.argv[1:] else []
