# Generated by Django 3.0.1 on 2020-04-25 05:58

import sys
from django.db import migrations

def load_fixture_statuses(apps, schema_editor):
    FixtureStatus = apps.get_model('home', 'FixtureStatus')
    fixture_statuses = []

    fixture_statuses.append(FixtureStatus(id=0, description='finished'))

    fixture_statuses.append(FixtureStatus(id=1, description='in-play'))

    fixture_statuses.append(FixtureStatus(id=2, description='paused'))

    fixture_statuses.append(FixtureStatus(id=3, description='postponed'))

    fixture_statuses.append(FixtureStatus(id=4, description='scheduled'))

    fixture_statuses.append(FixtureStatus(id=5, description='suspended'))

    fixture_statuses.append(FixtureStatus(id=6, description='awarded'))

    fixture_statuses.append(FixtureStatus(id=7, description='canceled'))
    
    for fixture_status in fixture_statuses:
        fixture_status.save()


def delete_fixture_statuses(apps, schema_editor):
    FixtureStatus = apps.get_model('home', 'FixtureStatus')
    FixtureStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_fixturestatus_fixturestatusmapping'),
    ]

    operations = [
        migrations.RunPython(load_fixture_statuses, delete_fixture_statuses)
    ] if 'test' not in sys.argv[1:] else []


