# Generated by Django 3.0.1 on 2019-12-31 19:51

from django.db import migrations
from home.constants import (
    get_fantasy_epl_api_id,
    get_football_data_dot_org_api_id
)
# BOOKMARK
def load_team_mappings(apps, schema_editor):
    TeamMapping = apps.get_model('home', 'TeamMapping')
#    fpl_arsenal_map = TeamMapping(id=0, 

def delete_team_mappings(apps, schema_editor):
    TeamMapping = apps.get_model('home', 'TeamMapping')
    TeamMapping.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_teams'),
    ]

    operations = [
       migrations.RunPython(load_team_mappings, delete_team_mappings) 
    ]
