# Generated by Django 3.0.1 on 2020-01-01 01:06

from django.db import migrations
from home.constants import api_identifiers_dict

def load_apis(apps, schema_editor):
    Api = apps.get_model('home', 'Api')
    api_fantasy_epl = Api(id=0, name="Fantasy EPL")
    api_fantasy_epl.save()

    api_football_data_dot_org = Api(id=1, name="football-data.org")
    api_football_data_dot_org.save()


def delete_apis(apps, schema_editor):
    Api = apps.get_model('home', 'Api')
    Api.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('home', 'populate_team_mappings'),
    ]

    operations = [
        migrations.RunPython(load_apis, delete_apis)
    ]
