# Generated by Django 3.0.1 on 2020-03-20 06:14

import sys
from django.db import migrations


def load_request_types(apps, schema_editor):
    RequestLimitType = apps.get_model('home', 'RequestType')
    
    request_type_fddo_matches = RequestLimitType(id=0, description="staggered",
                                                 base_url="https://api.football-data.org/v2/competitions/[Match ID]/matches",
                                                 current_version_iter=1, api_id=1)
    request_type_fddo_matches.save()


def delete_request_types(apps, schema_editor):
    RequestType = apps.get_model('home', 'RequestType')
    RequestType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_auto_20200320_0622')
    ]

    operations = [
        migrations.RunPython(load_request_types, delete_request_types)
    ] if 'test' not in sys.argv[1:] else []

